### ISSUE TITLE
脚本版本落后于 Greasyfork？

### ISSUE THREAD

**Issue by ivysrono** [backrunner/GreaseMonkeyJS#1]
[贴吧页面精简](https://greasyfork.org/zh-CN/scripts/23687) 在 greasyfork 已经 2.7.15 了，在 GitHub 才 2.7.9.
按说 greasyfork 是会自动从 GitHub同步过去的吧?

**Comment by backrunner** [comment]
首选同步源是Coding.net，Github这边因为学校网络问题只会偶尔推过来。
今后会保持两边版本同步的。
